### PR TITLE
Add OpenWatcom support

### PR DESCRIPTION
**Pull request by RamonUnch**
Add the `STDFAX_FPATH` macro so that stdfax is included via `\kilib\stdfax.h` so I do not need to duplicate the source tree. (messy but I do not know beter wcl386 flags.

* Fixes: #72 

Also adds the Help->About menu
* Progress on: #73 

* Progress on #15

### CODE REVIEW

**Comment by roytam1** [comment]
maybe we can just not using PCH and keep using relative path for atdafx.h instead.

**Comment by RamonUnch** [comment]
> maybe we can just not using PCH and keep using relative path for stdafx.h instead.

You are right indeed, I am just not familiar with the pre-compiled headers logic.

**Comment by roytam1** [comment]
actually PCH is working in WCC, but changing stdafx.h include path causes MSVC compilation failure.

**Comment by roytam1** [comment]
maybe we need to rename `kilib\string.h` to something like `kilib\kstring.h` to prevent conflict with system's `<string.h>`. some changes pushed to my branch and tested compiling with VC7.1/8 and WCC.

**Comment by RamonUnch** [comment]
> actually PCH is working in WCC, but changing stdafx.h include path causes MSVC compilation failure.

Disabling the pch inside the VC6 project file fixed it for me (in the Alt+F7 dialog).

**Comment by roytam1** [comment]
you didn't rename `string.h` to `kstring.h`, but adding new `kstring.h` here

**Pull request merged**
