### PR TITLE
Ole Drag and Drop

### PR DESCRIPTION
**Pull request by RamonUnch**
* Fixes: #70

First we must implement a basic IDropTarget derived class. Now we can drag links/text into the windows.

### CODE REVIEW

**Comment by roytam1** [comment]
look good, and by the way since yours have UAC related code, you have interested in this: https://stackoverflow.com/a/13587859

**Comment by RamonUnch** [comment]
I am becoming crazy with GCC, it seems it wants to replace InterlockedIncrement/Decrement with some pentium-style intrinsic and I see no way to prevent this. Because I use -march=i386, the intrinsic cannot be used and I link time error with `__sync_add/sub_and_fetch_4`.
I would simply like to use the real InterlockedIncrement from KERNEL32.DLL, it seems impossible with MingW64.

**Comment by roytam1** [comment]
> it seems it wants to replace InterlockedIncrement/Decrement with some pentium-style intrinsic

does this help? https://stackoverflow.com/a/57062793

**Comment by RamonUnch** [comment]
unfortunately `-fno-builtin` does not work, even `-ffreestanding` does not work.
I guess I will implement __sync_add/sub_and_fetch_4 that dynamically import from kERNEL32 just for gcc.

**Comment by RamonUnch** [comment]
MingW64 bug report: https://sourceforge.net/p/mingw-w64/bugs/961/

**Comment by RamonUnch** [comment]
Well the only way is to add:
```
	#undef InterlockedIncrement
	#undef InterlockedDecrement
	extern "C" WINBASEAPI LONG WINAPI InterlockedIncrement(LONG volatile *);
	extern "C" WINBASEAPI LONG WINAPI InterlockedDecrement(LONG volatile *);
```

**Comment by roytam1** [comment]
oh, at least they're still in libkernel32.a

**Comment by RamonUnch** [comment]
> oh, at least they're still in libkernel32.a

I checked that with a hex editor before resolving to the above solution.

**Comment by RamonUnch** [comment]
I am unsure of how to handle the full URL in MyPal68, I guess I should try to use the URL format `UniformResourceLocator` clipboard format that has to be registered with the `RegisterClipboardFormat()` function. Unfortunately it does not work.

* D&D Text/URL from IceApe-UXP: OK
* D&D Text from MyPal68: OK
* D&D URL from MyPal68 using the small lock before the URL: OK
* D&D URL after selecting the whole URL bar in MyPal68: NOT working!
* D&D a partial selecting of the URL in MyPal68 urlbar: OK
* D&D With the lock icon from 360Chrome: Not working!
* D&D the full selected URL from 360Chrome: OK

All of the above works with Metapad (simple RichEdit based txt editor, that I used to use before going to GreenPad). The RitchEdit control is responsible for this.

**Comment by roytam1** [comment]
> * D&D URL after selecting the whole URL bar in MyPal68: NOT working!

it is funny that VC6 OLE Client Test and DataObject Viewer don't accept dropping from mypal68

**Comment by roytam1** [comment]
had a look on ClipSpy ( https://www.codeproject.com/Articles/168/ClipSpy ), and I changed a bit in `OleDnDTarget`:
````c
	HRESULT STDMETHODCALLTYPE DragEnter(IDataObject *pDataObj, DWORD grfKeyState, POINTL pt, DWORD *pdwEffect)
	{
		*pdwEffect = DROPEFFECT_COPY; // <-----
		FORMATETC fmt = { CF_UNICODETEXT, NULL, DVASPECT_CONTENT, -1, TYMED_HGLOBAL };
	// ( ... )
	HRESULT STDMETHODCALLTYPE DragOver(DWORD grfKeyState, POINTL pt, DWORD *pdwEffect)
	{
		*pdwEffect = DROPEFFECT_COPY; // <-----
		return S_OK;
	}
````
and it seems working with mypal68.

**Comment by RamonUnch** [comment]
Indeed if I use `DROPEFFECT_COPY` in `DragOver()` and it works.

If you drag text from the RitchEdit control it moves it, even if I specify `DROPEFFECT_COPY` so I only will replace `DROPEFFECT_LINK` by `DROPEFFECT_COPY`, and I will leave the source to decide for the other cases.

**Comment by RamonUnch** [comment]
Well Firefox/UXP are buggy anyway as they pretend for a text selection that it can be moved when it can't so I ame forced to get the Move cursor when actually it will copy, but I prefer an inadequate icon that not being able to Move/Copy from WinWord/write and other well written control rather than having a slightly better drop cursor. just for firefox.

**Comment by roytam1** [comment]
just tested system icon data source, it works but unfortunately other applications expecting a file drop but not a text drop.

**Comment by roytam1** [comment]
> and another noticed thing is that, dragging text/system icon to clipspy shows nothing here.

ah, just saw `EnumFormatEtc` is unimplemented. thats why.

**Comment by roytam1** [comment]
anyway thanks for your great work, and by the way some other minor issues (besides mentioned above) found when I squashed merging to my tree and test:
- when dragging text, users expects caret following mouse cursor, and it doesn't for current implementation
- need undoing twice for undoing a mouse DnD of text inside same(main) edit control

**Comment by RamonUnch** [comment]
> ah, just saw EnumFormatEtc is unimplemented. thats why.

I need to do that then.

**Comment by RamonUnch** [comment]
> * when dragging text, users expects caret following mouse cursor, and it doesn't for current implementation 

True, I need to work on that, I might have to create a new caret because I do not want to disturb the current selection when dragging text.

> * need undoing twice for undoing a mouse DnD of text inside same(main) edit control

I am unsure on how to do that in a single undo.


Also I would like to handle Left Click dragging the edit view but it would require reworking on the left click handler.

**Comment by roytam1** [comment]
and for fun, I changed `IDataObjectTxt` to `IDataObjectFile` and `OleDnDSourceTxt` to `OleDnDSourceFile` to test a file drop:
````diff
diff --git a/GpMain.cpp b/GpMain.cpp
index 4e6f89c..753f986 100644
--- a/GpMain.cpp
+++ b/GpMain.cpp
@@ -157,7 +157,7 @@ LRESULT GreenPadWnd::on_message( UINT msg, WPARAM wp, LPARAM lp )
 			const unicode *fnu = filename_.ConvToWChar();
 			if( fnu )
 			{
-				OleDnDSourceTxt doDrag( fnu, my_lstrlenW(fnu), DROPEFFECT_COPY );
+				OleDnDSourceFile doDrag( fnu, my_lstrlenW(fnu), DROPEFFECT_COPY );
 				filename_.FreeWCMem(fnu);
 			}
 			break;
diff --git a/editwing/ip_cursor.cpp b/editwing/ip_cursor.cpp
index 511f5f3..87350ab 100644
--- a/editwing/ip_cursor.cpp
+++ b/editwing/ip_cursor.cpp
@@ -749,7 +749,7 @@ void Cursor::on_lbutton_up( short x, short y )
 
 bool Cursor::on_drag_start( short x, short y )
 {
-#ifndef NO_OLEDNDSRC
+#if 0//ndef NO_OLEDNDSRC
 	if( cur_ != sel_ )
 	{
 		VPos vp;
diff --git a/kilib/winutil.h b/kilib/winutil.h
index 2067b4c..baa910c 100644
--- a/kilib/winutil.h
+++ b/kilib/winutil.h
@@ -113,18 +113,18 @@ inline UINT Clipboard::RegisterFormat( const TCHAR* name )
 
 //=========================================================================
 //@{
-//	IDataObjectTxt: Class for a minimalist Text drag and drop data object
+//	IDataObjectFile: Class for a minimalist Text drag and drop data object
 //
-//	OleDnDSourceTxt(str, len) to do the drag and drop
+//	OleDnDSourceFile(str, len) to do the drag and drop
 //@}
 //=========================================================================
 
 #ifndef NO_OLEDNDSRC
 // Class for a minimalist Text drag and drop data object
-class IDataObjectTxt : public IDataObject, public Object
+class IDataObjectFile : public IDataObject, public Object
 {
 public:
-	IDataObjectTxt(const unicode *str, size_t len)
+	IDataObjectFile(const unicode *str, size_t len)
 		: refcnt( 1 )
 		, str_  ( str )
 		, len_  ( len )
@@ -149,7 +149,7 @@ private:
 		if( S_OK == QueryGetData(fmt) )
 		{
 			mem00( pm, sizeof(*pm) ); // In case...
-			pm->hGlobal = GlobalAlloc( GMEM_MOVEABLE, (len_+1)*sizeof(unicode) );
+			pm->hGlobal = GlobalAlloc( GMEM_MOVEABLE, sizeof(DROPFILES)+(len_+2)*sizeof(unicode) );
 			if( !pm->hGlobal )
 				return E_OUTOFMEMORY;
 			// Copy the data into pm
@@ -163,25 +163,18 @@ private:
 	HRESULT STDMETHODCALLTYPE GetDataHere(FORMATETC *fmt, STGMEDIUM *pm)
 	{
 		// Data is already allocated by caller!
-		VOID *data;
-		if( S_OK == QueryGetData(fmt) && pm->hGlobal != NULL && (data = GlobalLock(pm->hGlobal)) != NULL )
+		DROPFILES *data;
+		if( S_OK == QueryGetData(fmt) && pm->hGlobal != NULL && (data = (DROPFILES *)GlobalLock(pm->hGlobal)) != NULL )
 		{
-			if( fmt->cfFormat == CF_UNICODETEXT )
-			{
-				size_t len = Min(len_*sizeof(unicode), (size_t)GlobalSize(pm->hGlobal));
-				memmove( data, str_, len );
-				((unicode*)data)[len/sizeof(unicode)] = L'\0'; // NULL Terminate
-			}
-			else // if( fmt->cfFormat == CF_TEXT)
-			{	// Convert unicode string to ANSI.
-				int len = ::WideCharToMultiByte(CP_ACP, 0, str_, len_, NULL, 0, NULL, NULL);
-				char* ansi = new char[len];
-				len = ::WideCharToMultiByte(CP_ACP, 0, str_, len_, ansi, len, NULL, NULL);
-				len = Min(len*sizeof(char), (size_t)GlobalSize(pm->hGlobal));
-				memmove( data, (void*)ansi, len );
-				((char*)data)[len/sizeof(char)] = '\0'; // NULL Terminate
-				delete [] ansi;
-			}
+			size_t len = Min(len_*sizeof(unicode), (size_t)GlobalSize(pm->hGlobal));
+			data->pFiles=sizeof(DROPFILES);
+			data->pt.x=0;
+			data->pt.y=0;
+			data->fNC=1;
+			data->fWide=1;
+			memmove( ((char *)data)+sizeof(DROPFILES), str_, len );
+			*(((char *)data)+sizeof(DROPFILES)+len)='\0'; // NULL Terminate
+
 			GlobalUnlock(pm->hGlobal);
 			pm->pUnkForRelease = NULL; // Caller must free!
 			pm->tymed = TYMED_HGLOBAL;
@@ -193,7 +186,7 @@ private:
 	HRESULT STDMETHODCALLTYPE QueryGetData(FORMATETC *fmt)
 	{
 		// { CF_(UNI)TEXT, NULL, DVASPECT_CONTENT, -1, |TYMED_HGLOBAL } Only!
-		if( fmt->cfFormat == CF_UNICODETEXT || fmt->cfFormat == CF_TEXT )
+		if( fmt->cfFormat == CF_HDROP )
 			if( fmt->ptd == NULL
 			&&  fmt->dwAspect == DVASPECT_CONTENT
 		//	&&  fmt->lindex == -1 // Skip this one?
@@ -206,30 +199,7 @@ private:
 
 	HRESULT STDMETHODCALLTYPE GetCanonicalFormatEtc(FORMATETC *fmt, FORMATETC *fout)
 	{
-		if(fmt)
-		{
-			if(fmt->cfFormat == CF_UNICODETEXT || fmt->cfFormat == CF_TEXT )
-			{
-				if( fmt->dwAspect == DVASPECT_CONTENT
-				&&  fmt->lindex == -1 )
-				{
-					if (fout)
-					{
-						*fout = *fmt;
-						fout->ptd = NULL;
-					}
-					return DATA_S_SAMEFORMATETC;
-				}
-				if (fout) {
-					*fout = *fmt;
-					fout->ptd = NULL;
-					fout->dwAspect = DVASPECT_CONTENT;
-					fout->lindex = -1;
-					return S_OK;
-				}
-			}
-		}
-		const FORMATETC canon = { CF_UNICODETEXT, NULL, DVASPECT_CONTENT, -1, TYMED_HGLOBAL };
+		const FORMATETC canon = { CF_HDROP, NULL, DVASPECT_CONTENT, -1, TYMED_HGLOBAL };
 		*fout = canon;
 		return S_OK;
 	}
@@ -247,32 +217,32 @@ private:
 	const unicode *str_;
 	const size_t len_;
 };
-class OleDnDSourceTxt : public IDropSource
+class OleDnDSourceFile : public IDropSource
 {
 public:
-	OleDnDSourceTxt(const unicode *str, size_t len, DWORD adEffect = DROPEFFECT_MOVE|DROPEFFECT_COPY)
+	OleDnDSourceFile(const unicode *str, size_t len, DWORD adEffect = DROPEFFECT_MOVE|DROPEFFECT_COPY)
 	: refcnt    ( 1 )
 	, dwEffect_ ( 0 )
 	{
 		ki::app().InitModule( App::OLE );
 		{
 			// Create IData object from the string
-			IDataObjectTxt data(str, len);
-			LOGGER( "OleDnDSourceTxt IDataObjectTxt created" );
+			IDataObjectFile data(str, len);
+			LOGGER( "OleDnDSourceFile IDataObjectFile created" );
 			// Do the drag and drop and set dwEffect_ accordingly.
 			DWORD effect=0;
 			HRESULT ret = DoDragDrop( &data, this, adEffect, &effect );
 			// Only set the resulting effect if the drop was actually performed
 			if( ret == DRAGDROP_S_DROP )
 				dwEffect_ = effect;
-			LOGGER( "OleDnDSourceTxt DoDragDrop end" );
+			LOGGER( "OleDnDSourceFile DoDragDrop end" );
 		}
 	}
 
 	DWORD getEffect() const
 		{ return dwEffect_; }
 
-	~OleDnDSourceTxt(){}
+	~OleDnDSourceFile(){}
 private:
 	HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void **ppvObject)
 	{
````
it works, but our on_drop needs preprocessing so not to open file again if source hwnd equals to target hwnd.
maybe we need to merge 2 pairs of `OleDnDSourceXXX` and `IDataObjectXXX` into one to dedup codes.

**Comment by RamonUnch** [comment]
>  maybe we need to merge 2 pairs of OleDnDSourceXXX and IDataObjectXXX into one to dedup codes.

I was also working on this that but it is not yet working with explorer.exe, it works with other GreenPad windows to open a file when dragging in the non-client area. Also works with other programs. https://github.com/RamonUnch/GreenPad/commit/1f9439898229b9bff6e6a18e3facbac3b79a4d6c

**Comment by roytam1** [comment]
> it is not yet working with explorer.exe

because explorer.exe really wants to use `EnumFormatEtc`:
````c++
void SetFORMATETC(FORMATETC* pfe, UINT cf, TYMED tymed = TYMED_HGLOBAL, LONG lindex = -1,
    DWORD dwAspect = DVASPECT_CONTENT, DVTARGETDEVICE* ptd = NULL)
{
    pfe->cfFormat = (CLIPFORMAT)cf;
    pfe->tymed = tymed;
    pfe->lindex = lindex;
    pfe->dwAspect = dwAspect;
    pfe->ptd = ptd;
}
// Class for a minimalist Text drag and drop data object
class IDataObjectFile : public IDataObject, public Object
{
private:
	LONG refcnt;
	const unicode *str_;
	const size_t len_;

    enum {
        DATA_HDROP,
        DATA_NUM,
        DATA_INVALID = -1,
    };
	FORMATETC m_rgfe[DATA_NUM];
public:
	IDataObjectFile(const unicode *str, size_t len)
		: refcnt( 1 )
		, str_  ( str )
		, len_  ( len )
		{ SetFORMATETC(&m_rgfe[DATA_HDROP], CF_HDROP); }
	HRESULT STDMETHODCALLTYPE EnumFormatEtc(DWORD dwDirection, IEnumFORMATETC **ppefe)
	{
		if (dwDirection == DATADIR_GET) {
			// SHCreateStdEnumFmtEtc first appear in win2000, or you need to implement whole IEnumFORMATETC,
			// for example https://github.com/mirror/sevenzip/blob/master/CPP/7zip/UI/FileManager/EnumFormatEtc.cpp
			return SHCreateStdEnumFmtEtc(countof(m_rgfe), m_rgfe, ppefe);
		}
		*ppefe = NULL;
		return E_NOTIMPL;
	}
// (...)
````

**Comment by roytam1** [comment]
> not to open file again if source hwnd equals to target hwnd

seems not possible with `DragQueryFile` approach. we may have 2 options to workaround this:
a. "upgrading" GreenPadWnd to use OLE DnD, requires rewriting some portions
b. restricting greenpad not to open same file of opened file in current window. users may want to open not-yet-saved version of same file by DnDing and if this restriction is applied, users can no longer to do so.
c. do nothing, just document such behavior.

**Comment by RamonUnch** [comment]
Thanks for your patch, now it works fine on Win2K+
I Guess older windows will stay with a slightly limited drag and drop but it is not a big deal and might be implemented later.

I like the fact that you can drag the system icon in the non-client area of the same window and open a copy of the same file. Might be a little obscure but I do not see much problem. When dragging in the edit view, I like to see the full path to the file.
I also like that any selection can be considered like a file drop, (usefull when dealing with textfiles that are file lists lists).

Because I used the right click for dragging the explorer pops up the context  menu that is also quite useful.

I need now to to turn a multi line text in a multi-file HDROP source.

**Comment by roytam1** [comment]
porting CEnumFormatEtc from http://www.catch22.net/tuts/win32/enumerating-formatetc is almost painless.
https://github.com/roytam1/rtoss/commit/312e238bc30947589391602089bfca84b40112ff

**Comment by RamonUnch** [comment]
> and adding OLE DnD actually inflates code sizes a bit.

With GCC inflation is huge if you rely on -luuid, that is why I manually define GUIDs in the source. With VC++ I think there is no difference.

**Comment by RamonUnch** [comment]
Quite nice, however who is supposed to free the new `IEnumFORMATETC` structure, It cannot be possibly be the caller because we are using `new` and not GlobalAlloc or something. The `IEnumFORMATETC` destructor can destroy all data that were allocated by the object but not the object itself.

So We should create a `CEnumFORMATETC` object in the `IDataObject` constructor and give a pointer to it when asked by `EnumFormatEtc()` However I do not see how the `IEnumFORMATETC::Clone()` can be used.

**Comment by RamonUnch** [comment]
Well, I guess this is what AddRef() and Release() are all about.

**Comment by roytam1** [comment]
> Well, I guess this is what AddRef() and Release() are all about.

yeah, COM objects should free itself when ref count turns to zero.
https://github.com/roytam1/rtoss/commit/f40b68e1ab1cb4e6e5da3b842d0c9915858e1819

**Comment by RamonUnch** [comment]
On Win32s I get an `CO_E_OBJNOTCONNECTED` error (0x800401FDL) from DoDragDrop() when trying to drag from a GreenPad instance that received a drag from another GreenPad instance.
ie:
1) Open two instance of GreenPad, write text in one of them, drag it to the other instance => OK!
2) Try to drag back the text: Impossible, drag does not even starts and DoDragDrop fails with the above.
3) Try to drag again in the same order than the first time: Drag starts but the second instance fails to accept the drag.
4) Impossible to drag from GreenPad system Icon to WinFile
5) Everything works as expected if we only drag text within the same GreenPad instance.

**Comment by roytam1** [comment]
> 4\. Impossible to drag from GreenPad system Icon to WinFile

winfile doesn't implement OLE DnD. and still unavailable even in open sourced version: https://github.com/microsoft/winfile/search?q=CoInitialize

**Comment by RamonUnch** [comment]
> and for win32s ole dnd, there is a MSKB article: https://www.betaarchive.com/wiki/index.php?title=Microsoft_KB_Archive/122955

The link to the test program is dead :(

At some point I will have to port back WinFile to the older windows, but for now the original works fine enough for me.
How does WinFile handle drag and drop then? I need to investigate.

**Comment by roytam1** [comment]
> At some point I will have to port back WinFile to the older windows, but for now the original works fine enough for me.
> How does WinFile handle drag and drop then? I need to investigate.

https://github.com/microsoft/winfile/blob/068919f61dbc35cbf656ab14ebf19fceae68205e/src/wfdirsrc.c#L605

but it seems that it doesn't handle files dropping from other applications.

**Comment by RamonUnch** [comment]
Funny I realize that good old Win3.x has a cursor change when the target sets `DROPEFFECT_SCROLL`, it is no longer present on XP, even though it is a useful visual clue. I am missing something?

**Comment by roytam1** [comment]
I decided to unify fill-remaining-bytes process: https://github.com/roytam1/rtoss/commit/c0619249d3f741411a7437337dbfbd86182ac9f7

**Comment by RamonUnch** [comment]
> I decided to unify fill-remaining-bytes process: https://github.com/roytam1/rtoss/commit/c0619249d3f741411a7437337dbfbd86182ac9f7

Good idea, this ensure no extra junk data can be seen by the target.

**Comment by roytam1** [comment]
> On Win32s I get an `CO_E_OBJNOTCONNECTED` error (0x800401FDL) from DoDragDrop() when trying to drag from a GreenPad instance that received a drag from another GreenPad instance.

I tried to compile ClipSpy with VC4.1, it compiles but it crash in MFC40.dll when starting, maybe I just stuck in another rabbit hole.

**Comment by RamonUnch** [comment]
I think the problem is with IDropTarget on Win32s, because I can still drag from the sysmenu in an instance on which I already dragged to from another instance. However if I drag from the edit view it does not work.
I will check out ClipSpy.

**Comment by roytam1** [comment]
> I will check out ClipSpy.

fixed. hitting Q173027 ( https://jeffpar.github.io/kbarchive/kb/173/Q173027/ ). compiled binary startable in win32s 1.30c-FE.
[ClipSpy-vc4.zip](https://github.com/RamonUnch/GreenPad/files/10716595/ClipSpy-vc4.zip)

**Comment by roytam1** [comment]
> 2\. Try to drag back the text: Impossible, drag does not even starts and DoDragDrop fails with the above.

and further testing with winrar 2.50b1 and clipspy on win32s-1.30c-FE, anything dragging from winrar to clipspy's listview seems to be cancelled (showing normal cursor).

**Comment by RamonUnch** [comment]
ClipSpy seems now to behave nicely as a drop target on Win32s, the question is how we could do the same without MFC helpers? it uses `COleDropTarget` implemented in MFC40.DLL...

**Comment by RamonUnch** [comment]
You actually need to call `CoLockObjectExternal( this, TRUE, FALSE )` in the constructor of my implementation of IDropTarget and it works on Win32s. 
Also `CoLockObjectExternal( this, FALSE, TRUE)` should be called in the destructor as well.
I Just need to dynamically import this function and we are done!

**Comment by roytam1** [comment]
> You actually need to call `CoLockObjectExternal( this, TRUE, FALSE )` in the constructor of my implementation of IDropTarget and it works on Win32s.
> Also `CoLockObjectExternal( this, FALSE, TRUE)` should be called in the destructor as well.
> I Just need to dynamically import this function and we are done!

trying to drag text from office 4.3 to greenpad doesn't work here, why?

... `if( S_OK != MyCoLockObjectExternal( this, TRUE, FALSE ) )` shouldn't it be `==` in OleDnDTarget constructor?

fixed this and it works with office 4.3 now.

**Comment by RamonUnch** [comment]
> ... if( S_OK != MyCoLockObjectExternal( this, TRUE, FALSE ) ) shouldn't it be == in OleDnDTarget constructor?

Well I made two mistakes that compensated each other, that is why it worked for me, the other mistake is in `MyCoLockObjectExternal` that always return `E_NOTIMPL`, the fix is easy.

**Comment by roytam1** [comment]
BTW, win32s doesn't convert OLE CF_HDROP drop into old WM_DROPFILES. I wonder if we need to handle CF_HDROP as well?

**Comment by RamonUnch** [comment]
Nice, but now you should receive two `WM_DROPFILES` messages when dropping a file from explorer on newer Windows?

I was thinking also to send a WM_DROPFILE message to the other programs on which the user drops the system icon file. Like this we could drag and drop to WinFile.

This would require to track mouse movement when a drag starts and check GetWindowFromPoint(pt), then check if the window allows drop-file, and then on drop send the WM_DROPFILE. But I am not sure it would work.

**Comment by roytam1** [comment]
> Nice, but now you should receive two `WM_DROPFILES` messages when dropping a file from explorer on newer Windows?

yeah, I should put a win32s guard there.

**Comment by RamonUnch** [comment]
Is there any way to have OLE 2.0 on Windows NT3.1 or we need NT3.51 at least?
I cannot get OLE32 even with NT3.1 SP3 (build 528) NT3.51 works just fine though.
Maybe with NT3.5? but my NT3.5 environment is broken (even though it is a VM).

**Comment by roytam1** [comment]
> I cannot get OLE32 even with NT3.1 SP3 (build 528) NT3.51 works just fine though.
> Maybe with NT3.5? but my NT3.5 environment is broken (even though it is a VM).

OLE32 works since NT 3.5 Build 612. if you try to put 612's ole32.dll to NT 3.1 RTM, GreenPad stalls in OLE drop target creation.

**Comment by roytam1** [comment]
> but our on_drop needs preprocessing so not to open file again if source hwnd equals to target hwnd.

finally did it by adding extra fields after file list. https://github.com/roytam1/rtoss/commit/ee75ece1d334bd20c863cfd35424096247de633c

**Comment by roytam1** [comment]
> Like this we could drag and drop to WinFile.

for handling WinFile style DnD you may need some more codes:
https://github.com/OS2World/WIN16-Worplace-Shell-for-Windows/blob/55dab96b05dfccfcf1b53336ae57750a61e5206c/SOURCE/FOLDER.CPP#L129
https://github.com/OS2World/WIN16-Worplace-Shell-for-Windows/blob/55dab96b05dfccfcf1b53336ae57750a61e5206c/SOURCE/WPFLDR_2.CPP#L1937
https://github.com/OS2World/WIN16-Worplace-Shell-for-Windows/blob/55dab96b05dfccfcf1b53336ae57750a61e5206c/SOURCE/WPFLDR_1.CPP#L2449

**Comment by RamonUnch** [comment]
I think I will merge this branch now, (I like it as is).
I will see later on how to improve even more drag and drop.

Thanks a lot for your help!

**Comment by roytam1** [comment]
> I think I will merge this branch now, (I like it as is).

alright it looks like we both agreed current code is good enough to be merged, and I merged my version(favor) to my default branch. https://github.com/roytam1/rtoss/pull/4

**Comment by roytam1** [comment]
> Like this we could drag and drop to WinFile.

and I asked a question in `microsoft/winfile` repo about non-OLE Drag and Drop, and the answer from @malxau is worth to read:
https://github.com/microsoft/winfile/issues/378#issuecomment-1464841379

**Pull request merged**
