### PR TITLE
Fix statusbar for NT3.1 and Win95

### PR DESCRIPTION
**Pull request by RamonUnch**
Thanks @roytam1

### CODE REVIEW

**Comment by roytam1** [comment]
normally double-clicking status bar brings up re-open dialog, so ansi messages may need to be handled

**Comment by RamonUnch** [comment]
It does not seems the control sends send the WM_NOTIFY when clicking the satatusbar.
double-click works on NT3.5+, Win9x with the new toolbar class.
WM_NOTIFY does not depend on ANSI/Unicode stuff

**Comment by roytam1** [comment]
> double-click works on NT3.5+

checked it doesn't work on NT 3.50 RTM, also checked NT 3.50 Build 782 source in PRIVATE\WINDOWS\SHELL\COMMCTRL\STATUS.C and confirmed that there is no code to send NM_DBLCLK in early builds of common control status bar.

**Comment by roytam1** [comment]
but from my actual testing, NT < 3.51 doesn't even send any WM_NOTIFY from their common control status bar!

**Comment by RamonUnch** [comment]
You are right, I mixed 3.5 and 3.51, I retested making sure to use 3.50 build 800.1 and indeed no WM_NOTIFY message is sent. Maybe the COMCTL32 can be upgraded to the NT3.51 version on older NT3.x.

**Pull request merged**
