### PR TITLE
Allow TAB selection of extra Open/Save dialog items

### PR DESCRIPTION
**Pull request by RamonUnch**
* ADD the `DS_CONTROL` Style (`0x0400`)
* Dialog width should be 200 units
* Remove the dummy line and adjust position for other elements.

* Fixes: #83

Tested with:
1) Windows Server 2003 NT 5.2.3790
2) Windows 95 4.0.1111 (OSR2.5)
3) Chicago 347
4) Chicago 189
5) NT3.51sp5 + NewShell
6) Windows 95 4.0.708 Japanese
7) Windows NT 4.0.1166
8) Windows NT 4.0.1381 (SP6)
9) Windows 98 SE
10) Windows 2000 (NT 5.0.2195)

### CODE REVIEW

**Comment by roytam1** [comment]
changes that makes situation worse in Chicago Build 180.

Before:
image

After:
image

**Comment by RamonUnch** [comment]
Interesting that I do not have this problem with 189, are you sure you adjusted the Y position if the controls up to 0, they are low by default.
Anyway I will probably keep this funny line, because it is better to be on the safe side and it does not really hurt anything

**Comment by roytam1** [comment]
> are you sure you adjusted the Y position if the controls up to 0, they are low by default.

I copied all position changes from your change so it should be OK.

**Comment by RamonUnch** [comment]
Thanks for the info,

I am happy to have at least an accurate example of the use of this funny line.
I will add it back and add a comment explaining what it does so that people have an idea in the future.

**Pull request merged**
